name: Check deployment

on:
  workflow_dispatch:
  # Check the webpage every day
  schedule:
    - cron: "0 0 * * *"

jobs:
  check-webpage:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Hammerfight.io and ensure it's correct
        id: fetch-page
        run: |
          page=$(curl https://hammerfight.io)
          if echo "${page}" | grep -q "https://github.com/ivancea/hammerfight-io/"; then
            echo "error=false" >> $GITHUB_OUTPUT
          else
            echo "error=true" >> $GITHUB_OUTPUT
          fi

      - name: Notify new rules
        if: steps.fetch-page.outputs.error == 'false'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Hammerfight.io is down

      - name: Fail if there's an error
        if: steps.fetch-page.outputs.error == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Hammerfight.io is down')
